backend:
  name: github
  repo: kristianhaugen98/portfolio-project
  branch: main
media_folder: "public/images/uploads"
collections:
  - name: "hero"
    label: "Hero"
    folder: "content/hero"
    create: true
    slug: "data"
    fields:
      - { label: "Navn", name: "name", widget: "string" }
      - { label: "Intro", name: "intro", widget: "markdown" }
  - name: "about"
    label: "About"
    folder: "content/about"
    create: true
    slug: "data"
    fields:
      - { label: "Bio", name: "Bio", widget: "markdown" }
  - name: "skills"
    label: "Skills"
    folder: "content/skills"
    create: true
    slug: "data"
    fields:
      - { label: "Ferdighet", name: "skill", widget: "string" }
  - name: "projects"
    label: "Projects"
    folder: "content/projects"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Tittel", name: "title", widget: "string" }
      - { label: "Beskrivelse", name: "description", widget: "markdown" }
      - { label: "Tech Stack", name: "tech", widget: "list" }
      - { label: "Lenke", name: "link", widget: "string" }
      - { label: "Bilde", name: "image", widget: "image" }
